spring.application.name=camerbay
server.port=8082

# Database (local)
spring.datasource.url=jdbc:postgresql://91.99.165.29:5432/camerbay_andre
spring.datasource.username=andre
spring.datasource.password=U5zl+ZZ3Uw98@iirKC@e32-andre
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OAuth2 / Zitadel
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sso.afribytes.com
spring.security.oauth2.resourceserver.opaquetoken.client-id=352902506948395515
spring.security.oauth2.resourceserver.opaquetoken.client-secret=dgLfSmh55LEA06N8o3aj4H56kcT1gyTAm5e0Udslmod36qJgi0nwqdABH8Uwfpgt
spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://sso.afribytes.com/oauth/v2/introspect

# App
app.devMode=true
app.auth.project-id=347966106519994875

# Stream.io
stream.key=jm32jrzpj4nk
stream.secret=r5am56b3ymac6kwwsr3hq9kws693z5egu4t6tb3fqbdee8wx3nwe7gatj8dtpkg9
