spring.application.name=camerbay
server.port=8082

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# HTTP request logging
logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OAuth2 / Zitadel
spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:https://sso.afribytes.com}
spring.security.oauth2.resourceserver.opaquetoken.client-id=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_ID}
spring.security.oauth2.resourceserver.opaquetoken.client-secret=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_SECRET}
spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_INTROSPECTION_URI:https://sso.afribytes.com/oauth/v2/introspect}

# Custom properties
app.devMode=${APP_DEVMODE:false}
app.auth.project-id=${APP_AUTH_PROJECT_ID:347966106519994875}
stream.key=${STREAM_KEY}
stream.secret=${STREAM_SECRET}
